export const LOGIN_RESETPASSWORD_REQUEST = 'LOGIN_RESETPASSWORD_REQUEST';
export const LOGIN_RESETPASSWORD_RESPONSE = 'LOGIN_RESETPASSWORD_RESPONSE';
export const LOGIN_RESETPASSWORD_FAILED = 'LOGIN_RESETPASSWORD_FAILED';
export const LOG_RESETPASSWORD_OUT = 'LOG_RESETPASSWORD_OUT';
