export const LOGIN_REGISTER_REQUEST = 'LOGIN_REGISTER_REQUEST';
export const LOGIN_REGISTER_RESPONSE = 'LOGIN_REGISTER_RESPONSE';
export const LOGIN_REGISTER_FAILED = 'LOGIN_REGISTER_FAILED';
export const LOG_REGISTER_OUT = 'LOG_REGISTER_OUT';
